In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn import svm, datasets
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.utils.multiclass import unique_labels
from sklearn import metrics

dataset = pd.read_csv('/Users/kathiateran/Documents/Machine Learning/A1. FINAL/datasets/QCM7.csv', sep=',')
dataset

0.799_0.201  0.799_0.201.1  0.700_0.300  0.700_0.300.1  0.600_0.400  \
0        -11.23         -14.21       -18.71         -22.65       -27.32   
1        -12.44         -15.44       -21.13         -25.53       -30.45   
2        -13.75         -16.72       -24.00         -28.29       -33.91   
3        -15.05         -17.98       -26.42         -30.65       -36.56   
4        -16.67         -19.11       -28.69         -32.58       -39.62   
5        -35.68         -55.46       -44.41         -62.35       -56.36   
6        -34.99         -54.77       -45.11         -62.89       -56.03   
7        -35.99         -54.37       -45.34         -62.70       -54.89   
8        -35.85         -53.94       -45.24         -62.31       -53.55   
9        -35.88         -53.42       -45.30         -62.02       -53.81   
10       -31.86         -47.42       -45.81         -61.16       -61.55   
11       -32.66         -47.88       -46.52         -62.03       -62.06   
12       -33.08         -48.11       -47.17         -62.03       -61.91   
13       -33.24         -47.89       -47.07         -62.04       -60.93   
14       -33.97         -47.36       -47.83         -61.44       -60.91   
15       -26.80         -35.60       -36.76         -45.27       -44.80   
16       -25.81         -34.70       -36.48         -45.64       -43.29   
17       -25.49         -34.16       -36.67         -45.47       -42.21   
18       -25.41         -34.22       -36.30         -45.23       -40.97   
19       -26.78         -33.71       -36.78         -44.76       -41.49   
20       -27.45         -40.42       -42.10         -56.14       -58.24   
21       -28.79         -41.95       -43.33         -56.89       -59.68   
22       -29.59         -42.61       -43.82         -57.46       -60.44   
23       -29.98         -42.70       -44.41         -57.80       -60.99   
24       -30.95         -42.82       -45.26         -57.19       -62.17   

    0.600_0.400.1  0.501_0.499  0.501_0.499.1  0.400_0.600  0.400_0.600.1  \
0          -32.39       -35.28         -40.72       -40.63         -49.87   
1          -36.22       -36.85         -45.11       -45.40         -55.16   
2          -39.95       -40.96         -49.43       -49.91         -60.11   
3          -43.00       -43.81         -52.73       -53.89         -64.35   
4          -45.68       -47.16         -55.65       -57.20         -67.68   
5          -72.43       -66.26         -80.33       -79.56         -91.76   
6          -72.68       -65.75         -80.24       -76.75         -89.86   
7          -71.23       -64.63         -79.05       -74.92         -88.07   
8          -69.54       -63.43         -77.51       -73.38         -86.43   
9          -68.74       -62.30         -76.12       -72.33         -84.57   
10         -76.42       -76.12         -89.12       -94.11        -104.97   
11         -77.14       -77.12         -90.14       -93.95        -105.24   
12         -76.65       -76.94         -89.64       -93.07        -103.93   
13         -75.29       -75.37         -87.80       -91.04        -101.96   
14         -72.88       -75.20         -85.82       -89.76         -99.85   
15         -53.48       -51.52         -59.54       -60.38         -67.51   
16         -51.95       -50.28         -58.17       -57.74         -65.20   
17         -50.90       -48.84         -56.82       -56.00         -63.28   
18         -49.57       -48.07         -55.73       -54.33         -61.54   
19         -48.17       -48.57         -54.13       -54.94         -60.11   
20         -72.12       -76.97         -90.61       -99.22        -112.17   
21         -73.88       -78.96         -93.10      -101.14        -114.64   
22         -74.61       -80.18         -94.38      -101.48        -115.36   
23         -75.15       -80.38         -94.50      -100.91        -114.82   
24         -75.36       -80.85         -93.97      -100.50        -113.82   

    Class  
0       0  
1       0  
2       0  
3 

In [2]:
X = dataset.iloc[:, 0:10].values
y = dataset.iloc[:, 10].values

In [3]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [4]:
from sklearn.svm import SVC

classifier = SVC(kernel='poly',C=1000, degree=3, gamma='auto')

classifier.fit(X_train, y_train)

pred_train_poly = classifier.predict(X_train)
pred_test_poly = classifier.predict(X_test)

print('\nPrediction accuracy for the training dataset')
print('{:.2%}\n'.format(metrics.accuracy_score(y_train, pred_train_poly)))


print('Prediction accuracy for the test dataset')
print('{:.2%}\n'.format(metrics.accuracy_score(y_test, pred_test_poly)))

print('Confusion Matrix')
print(metrics.confusion_matrix(y_test, pred_test_poly))


Prediction accuracy for the training dataset
100.00%

Prediction accuracy for the test dataset
100.00%

Confusion Matrix
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 2]]


In [5]:
conf_mat=metrics.confusion_matrix(y_test, pred_test_poly)

True_Positive = conf_mat[0][0]
False_Positive = conf_mat[0][1]
False_Negative = conf_mat[1][0]
True_Negative = conf_mat[1][1]

print("True Positive: ", True_Positive)
print("False Positive: ", False_Positive)
print("False Negative: ", False_Negative)
print("True Negative: ", True_Negative)

True Positive:  1
False Positive:  0
False Negative:  0
True Negative:  1


In [7]:
from sklearn.metrics import classification_report
print("Classification Report:\n\n",classification_report(y_test, pred_test_poly))

Classification Report:

               precision    recall  f1-score   support

           0       1.00      1.00      1.00         1
           1       1.00      1.00      1.00         1
           2       1.00      1.00      1.00         1
           3       1.00      1.00      1.00         2

    accuracy                           1.00         5
   macro avg       1.00      1.00      1.00         5
weighted avg       1.00      1.00      1.00         5

