In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn import svm, datasets
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.utils.multiclass import unique_labels
from sklearn import metrics

dataset = pd.read_csv('/Users/kathiateran/Documents/Machine Learning/A1. FINAL/datasets/QCM10.csv', sep=',')
dataset

0.799_0.201  0.799_0.201.1  0.700_0.300  0.700_0.300.1  0.600_0.400  \
0        -11.98         -10.99       -19.12         -17.28       -33.13   
1        -12.15         -11.33       -22.33         -19.95       -39.82   
2        -12.58         -11.74       -26.67         -23.34       -46.48   
3        -13.79         -12.82       -30.56         -26.18       -52.30   
4        -15.73         -13.87       -34.54         -28.65       -57.44   
5        -58.41         -38.66       -83.58         -57.33      -110.24   
6        -59.68         -40.01       -84.75         -58.75      -109.91   
7        -60.12         -40.73       -85.19         -59.47      -108.08   
8        -60.41         -41.20       -84.73         -59.31      -106.46   
9        -60.87         -39.88       -84.22         -57.58      -105.32   
10       -59.41         -61.86       -91.65         -81.02      -131.05   
11       -61.16         -62.92       -93.55         -82.39      -133.11   
12       -61.80         -62.99       -94.15         -82.45      -133.24   
13       -61.94         -62.78       -94.46         -82.39      -131.54   
14       -62.34         -61.87       -95.09         -81.53      -128.23   
15       -44.10         -35.02       -66.13         -50.43       -90.29   
16       -44.67         -35.39       -66.62         -50.84       -84.41   
17       -44.50         -35.27       -66.60         -50.98       -80.79   
18       -44.34         -34.97       -66.58         -50.93       -78.07   
19       -44.80         -35.17       -66.20         -50.42       -76.80   
20       -52.22         -41.67       -75.74         -57.70      -109.10   
21       -54.15         -42.91       -77.43         -59.33      -112.04   
22       -54.72         -43.04       -78.19         -60.05      -113.36   
23       -54.54         -42.61       -78.67         -60.59      -114.31   
24       -54.47         -41.87       -79.15         -60.58      -115.72   

    0.600_0.400.1  0.501_0.499  0.501_0.499.1  0.400_0.600  0.400_0.600.1  \
0          -28.45       -48.83         -40.77       -62.49         -50.82   
1          -33.64       -56.90         -46.77       -73.32         -58.96   
2          -38.69       -65.95         -53.46       -84.53         -67.21   
3          -42.98       -73.81         -59.19       -94.41         -74.40   
4          -46.26       -80.37         -63.49      -102.94         -80.25   
5          -76.80      -133.77         -96.13      -171.05        -124.15   
6          -77.28      -130.65         -94.69      -161.81        -118.70   
7          -76.43      -127.51         -92.88      -155.54        -114.76   
8          -75.39      -124.62         -90.88      -151.56        -112.58   
9          -73.36      -122.59         -88.28      -146.99        -109.52   
10        -105.51      -165.68        -126.30      -207.16        -153.44   
11        -107.27      -168.62        -128.94      -210.85        -157.01   
12        -107.15      -165.33        -126.55      -204.60        -152.81   
13        -105.60      -160.74        -123.08      -195.49        -146.26   
14        -102.05      -156.31        -119.71      -187.95        -140.79   
15         -68.00      -101.74         -76.53      -117.67         -88.63   
16         -63.94       -97.11         -73.35      -111.06         -83.98   
17         -61.24       -93.34         -70.67      -106.18         -80.45   
18         -59.27       -89.95         -68.18      -101.46         -77.06   
19         -58.26       -87.09         -65.55       -98.14         -73.89   
20         -83.42      -149.62        -114.96      -197.35        -151.92   
21         -86.16      -155.04        -119.56      -205.77        -159.30   
22         -87.50      -157.68        -121.95      -207.96        -161.60   
23         -88.44      -158.35        -122.77      -207.15        -161.37   
24         -89.26      -159.23        -122.95      -200.98        -157.18   

    Class  
0       0  
1       0  
2       0  
3 

In [2]:
X = dataset.iloc[:, 0:10].values
y = dataset.iloc[:, 10].values

In [3]:
from sklearn.svm import SVC

clf_linear = svm.SVC(kernel='linear', C=1.0, gamma='auto')

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

clf_linear.fit(X_train, y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto', kernel='linear',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [4]:
pred_train_linear = clf_linear.predict(X_train)
pred_test_linear = clf_linear.predict(X_test)

print('\nPrediction accuracy for the training dataset')
print('{:.2%}\n'.format(metrics.accuracy_score(y_train, pred_train_linear)))

print('Prediction accuracy for the test dataset')
print('{:.2%}\n'.format(metrics.accuracy_score(y_test, pred_test_linear)))

print('Confusion Matrix')
print(metrics.confusion_matrix(y_test, pred_test_linear))


Prediction accuracy for the training dataset
100.00%

Prediction accuracy for the test dataset
100.00%

Confusion Matrix
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 2]]


In [5]:
conf_mat=metrics.confusion_matrix(y_test, pred_test_linear)

True_Positive = conf_mat[0][0]
False_Positive = conf_mat[0][1]
False_Negative = conf_mat[1][0]
True_Negative = conf_mat[1][1]

print("True Positive: ", True_Positive)
print("False Positive: ", False_Positive)
print("False Negative: ", False_Negative)
print("True Negative: ", True_Negative)

True Positive:  1
False Positive:  0
False Negative:  0
True Negative:  1


In [7]:
from sklearn.metrics import classification_report
print("Classification Report:\n\n",classification_report(y_test,pred_test_linear))

Classification Report:

               precision    recall  f1-score   support

           0       1.00      1.00      1.00         1
           1       1.00      1.00      1.00         1
           2       1.00      1.00      1.00         1
           3       1.00      1.00      1.00         2

    accuracy                           1.00         5
   macro avg       1.00      1.00      1.00         5
weighted avg       1.00      1.00      1.00         5

