In [1]:
%matplotlib inline
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.utils.multiclass import unique_labels


In [2]:
dataset = pd.read_csv('/Users/kathiateran/Documents/Machine Learning/A1. FINAL/datasets/QCM6.csv', sep=',')
dataset

0.799_0.201  0.799_0.201.1  0.700_0.300  0.700_0.300.1  0.600_0.400  \
0        -11.82         -13.29       -19.32         -26.28       -38.14   
1        -11.54         -14.18       -25.35         -32.75       -48.77   
2        -12.45         -15.81       -33.33         -40.64       -61.50   
3        -14.67         -18.49       -40.56         -47.67       -72.11   
4        -18.07         -19.74       -47.08         -53.50       -81.15   
5        -98.63         -97.92      -137.15        -131.93      -191.17   
6        -96.62         -96.50      -136.86        -131.75      -192.76   
7        -95.58         -95.61      -137.43        -132.20      -193.50   
8        -94.48         -94.49      -136.49        -132.39      -193.90   
9        -94.04         -93.29      -136.13        -130.11      -194.96   
10       -90.31         -97.75      -159.99        -153.60      -248.81   
11       -93.79         -99.97      -164.98        -156.41      -255.59   
12       -95.86        -101.04      -168.38        -157.85      -259.27   
13       -97.70        -102.02      -172.03        -158.71      -261.38   
14       -98.99        -101.34      -174.99        -157.25      -258.76   
15       -68.13         -53.77      -108.27         -91.80      -153.07   
16       -69.54         -55.73      -109.49         -93.98      -151.26   
17       -70.31         -57.01      -110.39         -95.45      -144.23   
18       -70.40         -57.63      -110.03         -95.97      -137.89   
19       -71.48         -57.84      -110.46         -95.21      -134.85   
20       -66.05         -55.55      -136.84        -112.44      -211.41   
21       -73.04         -60.95      -141.43        -116.96      -217.81   
22       -76.09         -63.93      -143.70        -119.61      -221.81   
23       -78.81         -65.68      -146.01        -121.49      -223.79   
24       -82.17         -67.91      -149.03        -123.40      -225.73   

    0.600_0.400.1  0.501_0.499  0.501_0.499.1  0.400_0.600  0.400_0.600.1  \
0          -50.09       -59.78         -75.04       -85.63        -104.66   
1          -60.08       -75.41         -89.72      -104.25        -121.90   
2          -72.12       -91.75        -104.67      -124.21        -139.76   
3          -82.19      -106.26        -118.26      -141.95        -155.84   
4          -89.81      -117.91        -128.10      -156.66        -168.72   
5         -180.52      -260.06        -240.69      -352.22        -321.20   
6         -182.30      -264.07        -245.29      -357.64        -327.04   
7         -183.30      -266.77        -248.06      -359.32        -329.25   
8         -184.20      -267.82        -249.31      -361.72        -331.38   
9         -183.40      -267.72        -249.56      -360.72        -330.82   
10        -219.47      -337.16        -287.02      -427.01        -360.56   
11        -223.56      -341.09        -289.88      -426.05        -360.56   
12        -224.68      -336.37        -285.85      -413.52        -351.05   
13        -224.80      -328.87        -278.99      -395.35        -334.79   
14        -222.10      -318.91        -269.47      -383.93        -325.01   
15        -135.10      -181.96        -165.24      -216.15        -202.26   
16        -134.78      -174.59        -161.28      -205.61        -195.44   
17        -129.90      -168.80        -157.56      -198.45        -190.72   
18        -125.45      -163.89        -154.37      -192.03        -186.27   
19        -122.39      -160.98        -152.93      -187.98        -183.80   
20        -176.55      -300.14        -252.75      -417.08        -353.50   
21        -183.10      -309.05        -261.66      -429.28        -365.93   
22        -187.00      -313.96        -266.76      -436.02        -372.47   
23        -189.51      -319.61        -271.93      -439.91        -376.66   
24        -191.28      -322.75        -274.53      -447.74        -381.94   

    Class  
0       0  
1       0  
2       0  
3 

In [3]:
X = dataset.iloc[:, 0:10].values
y = dataset.iloc[:, 10].values

In [4]:
# Splitting the dataset:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [5]:
from sklearn import metrics
from hmmlearn import hmm
from hmmlearn.hmm import GaussianHMM

hmm_clf = GaussianHMM(n_components=5, covariance_type='diag', n_iter=10000).fit(X)

pred_train_hmm = hmm_clf.predict(X_train)
pred_test_hmm = hmm_clf.predict(X_test)

print('\nPrediction accuracy for the training dataset')
print('{:.2%}\n'.format(metrics.accuracy_score(y_train, pred_train_hmm)))

print('Prediction accuracy for the test dataset')
print('{:.2%}\n'.format(metrics.accuracy_score(y_test, pred_test_hmm)))

print('Confusion Matrix')
print(metrics.confusion_matrix(y_test, pred_test_hmm))


Prediction accuracy for the training dataset
30.00%

Prediction accuracy for the test dataset
20.00%

Confusion Matrix
[[0 0 1 0]
 [0 0 1 0]
 [0 0 1 0]
 [0 0 2 0]]


In [6]:
from sklearn.metrics import confusion_matrix
conf_mat=confusion_matrix(y_test, pred_test_hmm)

True_Positive = conf_mat[0][0]
False_Positive = conf_mat[0][1]
False_Negative = conf_mat[1][0]
True_Negative = conf_mat[1][1]

print("True Positive: ", True_Positive)
print("False Positive: ", False_Positive)
print("False Negative: ", False_Negative)
print("True Negative: ", True_Negative)

True Positive:  0
False Positive:  0
False Negative:  0
True Negative:  0


In [8]:
from sklearn.metrics import classification_report
print("Classification Report:\n\n",classification_report(y_test,pred_test_hmm))

Classification Report:

               precision    recall  f1-score   support

           0       0.00      0.00      0.00         1
           1       0.00      0.00      0.00         1
           2       0.20      1.00      0.33         1
           3       0.00      0.00      0.00         2

    accuracy                           0.20         5
   macro avg       0.05      0.25      0.08         5
weighted avg       0.04      0.20      0.07         5

