In [14]:
%matplotlib inline
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import metrics

dataset = pd.read_csv('/Users/kathiateran/Documents/Machine Learning/A1. FINAL/datasets/QCM12.csv', sep=',')
dataset

0.799_0.201  0.799_0.201.1  0.700_0.300  0.700_0.300.1  0.600_0.400  \
0         -9.40          -7.95       -21.44         -17.46       -34.39   
1        -13.18         -12.01       -26.46         -22.75       -41.48   
2        -18.61         -16.29       -32.84         -28.72       -49.32   
3        -21.88         -19.81       -38.18         -33.77       -56.27   
4        -24.84         -22.36       -42.61         -37.94       -60.47   
5        -48.45         -56.17       -94.77         -87.56      -144.20   
6        -52.71         -59.26       -98.57         -89.20      -149.15   
7        -57.09         -60.88      -100.87         -90.63      -153.09   
8        -60.23         -61.76      -106.92         -91.52      -157.94   
9        -62.88         -62.89      -108.56         -93.26      -157.61   
10       -62.12         -65.95      -111.79        -109.16      -171.12   
11       -74.65         -68.38      -116.27        -109.51      -173.44   
12       -80.61         -69.71      -119.26        -110.41      -175.38   
13       -81.01         -70.72      -126.52        -110.98      -183.94   
14       -86.34         -71.04      -129.71        -112.33      -182.08   
15       -60.65         -56.38      -105.31         -86.28      -148.30   
16       -62.54         -56.68      -104.33         -85.74      -147.54   
17       -66.37         -57.25      -104.69         -85.93      -150.89   
18       -69.99         -57.49      -109.66         -86.03      -149.90   
19       -69.99         -58.49      -110.79         -86.69      -153.44   
20       -54.35         -56.09       -88.23         -90.54      -128.65   
21       -56.14         -57.35       -90.74         -92.60      -132.16   
22       -57.71         -58.37       -92.83         -93.91      -134.83   
23       -58.36         -58.92       -94.31         -95.13      -136.44   
24       -59.00         -59.26       -94.97         -95.51      -137.28   

    0.600_0.400.1  0.501_0.499  0.501_0.499.1  0.400_0.600  0.400_0.600.1  \
0          -27.35       -48.61         -39.91       -63.62         -53.14   
1          -34.60       -56.74         -48.68       -73.45         -63.17   
2          -42.29       -65.87         -57.89       -84.45         -73.99   
3          -48.93       -74.09         -65.99       -92.61         -83.37   
4          -53.86       -80.67         -72.62      -101.14         -91.33   
5         -125.19      -203.85        -167.42      -263.80        -218.03   
6         -126.75      -206.98        -169.59      -269.29        -220.77   
7         -127.88      -210.05        -170.99      -274.14        -222.00   
8         -128.49      -210.78        -171.39      -274.14        -221.00   
9         -129.42      -214.45        -171.58      -277.29        -219.58   
10        -155.86      -223.76        -209.93      -288.01        -269.96   
11        -157.52      -228.82        -212.00      -292.81        -272.04   
12        -158.87      -231.08        -213.05      -296.68        -271.47   
13        -159.84      -230.44        -213.17      -294.04        -269.00   
14        -160.74      -229.94        -211.24      -294.20        -266.83   
15        -117.76      -180.36        -137.76      -219.73        -164.51   
16        -114.04      -182.08        -133.10      -217.25        -159.49   
17        -109.68      -178.98        -129.79      -211.37        -155.89   
18        -106.50      -186.32        -127.54      -213.69        -153.26   
19        -104.72      -183.04        -126.16      -210.51        -150.14   
20        -132.19      -173.71        -179.36      -231.30        -239.19   
21        -135.36      -178.79        -183.93      -239.06        -246.53   
22        -137.56      -182.33        -187.16      -243.12        -250.30   
23        -138.96      -184.70        -189.32      -246.15        -252.80   
24        -139.36      -186.98        -191.19      -248.98        -255.23   

    Class  
0       0  
1       0  
2       0  
3 

In [15]:
X = dataset.iloc[:, 0:10].values
y = dataset.iloc[:, 10].values

In [16]:
# Splitting the dataset:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [17]:
#K-NEIGHBOR
from sklearn.neighbors import KNeighborsClassifier

knn_clf = KNeighborsClassifier(n_neighbors=5, metric='minkowski', p=2)

knn_clf.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [18]:
pred_train_knn = knn_clf.predict(X_train)
pred_test_knn = knn_clf.predict(X_test)

print('\nPrediction accuracy for the training dataset')
print('{:.2%}\n'.format(metrics.accuracy_score(y_train, pred_train_knn)))

print('Prediction accuracy for the test dataset')
print('{:.2%}\n'.format(metrics.accuracy_score(y_test, pred_test_knn)))

print('Confusion Matrix')
print(metrics.confusion_matrix(y_test, pred_test_knn)) 


Prediction accuracy for the training dataset
100.00%

Prediction accuracy for the test dataset
100.00%

Confusion Matrix
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 2]]


In [19]:
conf_mat=metrics.confusion_matrix(y_test, pred_test_knn)

True_Positive = conf_mat[0][0]
False_Positive = conf_mat[0][1]
False_Negative = conf_mat[1][0]
True_Negative = conf_mat[1][1]

print("True Positive: ", True_Positive)
print("False Positive: ", False_Positive)
print("False Negative: ", False_Negative)
print("True Negative: ", True_Negative)

True Positive:  1
False Positive:  0
False Negative:  0
True Negative:  1


In [20]:
from sklearn.metrics import classification_report
print("Classification Report:\n\n",classification_report(y_test, pred_test_knn))

Classification Report:

               precision    recall  f1-score   support

           0       1.00      1.00      1.00         1
           1       1.00      1.00      1.00         1
           2       1.00      1.00      1.00         1
           3       1.00      1.00      1.00         2

    accuracy                           1.00         5
   macro avg       1.00      1.00      1.00         5
weighted avg       1.00      1.00      1.00         5

